from __future__ import annotations

from typing import Any


# These are versioned acceptance universes, not official joint estimates.  Cases
# 2–10 use deliberately wide scenario priors over an official entity-unit
# control and never multiply unsupported marginal percentages.
REQUIRED_PARENT_CASES: tuple[dict[str, Any], ...] = (
    {
        "case_id":"PARENT-01",
        "description":"홈페이지가 없는 60대 음식점 사장 또는 사업체",
        "domain_code":"small_business_digital",
        "entity_unit":"enterprise",
        "linked_parent_archetype_id":"ARC-06-001",
        "condition":{"feature_code":"small_business_digital.consumption_mode","value":"대표자 직접"},
        "rule":{"and":["restaurant_or_bar_enterprise","owner_age_60_69_proxy","website_absence_scenario"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-02",
        "description":"초등학생 자녀가 있는 수도권 맞벌이 가구",
        "domain_code":"education_learning",
        "entity_unit":"household",
        "control_id":"CTL-HH-CHILD18-2024",
        "share":{"low":0.06,"base":0.12,"high":0.22},
        "condition":{"feature_code":"education_learning.decision_unit","value":"보호자·가족"},
        "rule":{"and":["capital_region","elementary_child","dual_income_household"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-03",
        "description":"반려동물을 키우면서 국내여행 빈도가 높은 30~40대 가구",
        "domain_code":"pets",
        "entity_unit":"household",
        "control_id":"CTL-HH-TOTAL-2024",
        "share":{"low":0.003,"base":0.010,"high":0.025},
        "condition":{"feature_code":"pets.occasion","value":"외출·여행"},
        "rule":{"and":["pet_household","frequent_domestic_travel","adult_age_30_49"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-04",
        "description":"직원 5명 미만이고 온라인 판매채널이 없는 지방 식품 소매업체",
        "domain_code":"small_business_digital",
        "entity_unit":"enterprise",
        "control_id":"CTL-ENT-ALL-2024",
        "share":{"low":0.001,"base":0.004,"high":0.012},
        "condition":{"feature_code":"small_business_digital.consumption_mode","value":"대표자 직접"},
        "rule":{"and":["non_capital_region","food_retail","employees_under_5","no_online_sales_channel"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-05",
        "description":"사교육을 이용하지만 현재 서비스에 불만이 있는 중학생 보호자 가구",
        "domain_code":"education_learning",
        "entity_unit":"household",
        "control_id":"CTL-HH-CHILD18-2024",
        "share":{"low":0.015,"base":0.060,"high":0.140},
        "condition":{"feature_code":"education_learning.barrier_risk_trust","value":"학습 품질"},
        "rule":{"and":["middle_school_child","private_education_use","current_service_dissatisfaction"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-06",
        "description":"모바일 사용은 높지만 사업 디지털화가 낮은 소상공인",
        "domain_code":"small_business_digital",
        "entity_unit":"enterprise",
        "control_id":"CTL-ENT-ALL-2024",
        "share":{"low":0.025,"base":0.080,"high":0.180},
        "condition":{"feature_code":"small_business_digital.barrier_risk_trust","value":"디지털 학습 부담"},
        "rule":{"and":["small_business","high_mobile_use","low_business_digitization"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-07",
        "description":"은퇴 전후 부모·배우자 돌봄 부담이 있는 50~60대 가구",
        "domain_code":"senior_retirement_care",
        "entity_unit":"household",
        "control_id":"CTL-HH-TOTAL-2024",
        "share":{"low":0.020,"base":0.060,"high":0.130},
        "condition":{"feature_code":"senior_retirement_care.object","value":"건강·요양"},
        "rule":{"and":["adult_age_50_69","near_retirement","parent_or_spouse_care_burden"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-08",
        "description":"영유아 자녀를 둔 맞벌이 보호자 가구",
        "domain_code":"parenting_childcare",
        "entity_unit":"household",
        "control_id":"CTL-HH-CHILD18-2024",
        "share":{"low":0.040,"base":0.120,"high":0.240},
        "condition":{"feature_code":"parenting_childcare.motivation_job","value":"일·가정 양립"},
        "rule":{"and":["child_age_0_5","dual_income_household","guardian_decision_unit"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-09",
        "description":"고빈도 국내여행 1인 가구",
        "domain_code":"travel_hospitality",
        "entity_unit":"household",
        "control_id":"CTL-HH-GENERAL-SIZE1-2024",
        "share":{"low":0.015,"base":0.060,"high":0.140},
        "condition":{"feature_code":"travel_hospitality.object","value":"국내 단기여행"},
        "rule":{"and":["one_person_household","frequent_domestic_travel"]},
        "required_tags":[],
    },
    {
        "case_id":"PARENT-10",
        "description":"비용민감도와 편의중시가 동시에 높은 중복 tag 사례",
        "domain_code":"dining_delivery_cafe",
        "entity_unit":"person",
        "control_id":"CTL-ADULT-19P-RESIDENT-2024-12",
        "share":{"low":0.025,"base":0.090,"high":0.200},
        "condition":{"feature_code":"dining_delivery_cafe.motivation_job","value":"편의"},
        "rule":{"and":["price_sensitive_tag","convenience_orientation_tag"]},
        "required_tags":["편의","배달비·가격"],
    },
)


CROSS_CASES: tuple[dict[str, Any], ...] = (
    {"case_id":"CROSS-01","description":"반려동물을 키우고 국내여행이 잦으며 차량 이동을 선호하는 30~40대 가구","domains":["pets","travel_hospitality","mobility_automotive"],"constraints":{"age_min":30,"age_max":49},"output_unit":"household","semantic_conditions":["pet ownership proxy","frequent domestic travel","vehicle preference"],"scenario_overlay":{"low":0.05,"base":0.20,"high":0.50}},
    {"case_id":"CROSS-02","description":"음악 숏폼 발견 비중이 높고 OTT 광고형을 이용하는 10~20대","domains":["music_audio","video_ott"],"constraints":{"age_min":20,"age_max":29},"output_unit":"person","semantic_conditions":["short-form music discovery","ad-supported OTT"],"scenario_overlay":{"low":0.08,"base":0.25,"high":0.55},"uncovered_population":"age 10–19 requires a youth behavior joint; result covers age 20–29 only"},
    {"case_id":"CROSS-03","description":"홈트레이닝과 건강식품 정기구매가 결합된 1인 가구","domains":["sports_outdoor","grocery_home_meals"],"constraints":{"family_type_contains":"혼자"},"output_unit":"household","semantic_conditions":["home training","recurring online health-food purchase"],"scenario_overlay":{"low":0.04,"base":0.15,"high":0.40}},
    {"case_id":"CROSS-04","description":"자녀 교육·문화·여행 지출이 모두 높은 수도권 맞벌이 가구","domains":["education_learning","culture_events","travel_hospitality"],"constraints":{"province":"경기","family_type_contains":"자녀"},"output_unit":"household","semantic_conditions":["dual income","high education/culture/travel spend"],"scenario_overlay":{"low":0.03,"base":0.12,"high":0.35}},
    {"case_id":"CROSS-05","description":"온라인 장보기와 배달외식 빈도가 모두 높은 영유아 가구","domains":["grocery_home_meals","dining_delivery_cafe"],"constraints":{"family_type_contains":"자녀"},"output_unit":"household","semantic_conditions":["young child household","high online grocery and delivery frequency"],"scenario_overlay":{"low":0.04,"base":0.16,"high":0.42}},
    {"case_id":"CROSS-06","description":"공연·음반·굿즈 지출이 높은 아티스트 팬덤","domains":["music_audio","social_creator"],"constraints":{},"output_unit":"person","semantic_conditions":["artist fandom","high concert/album/merchandise spend"],"scenario_overlay":{"low":0.03,"base":0.12,"high":0.32}},
    {"case_id":"CROSS-07","description":"아웃도어 활동과 국내 숙박여행·장비구매가 결합된 가구","domains":["sports_outdoor","travel_hospitality","fashion_resale"],"constraints":{},"output_unit":"household","semantic_conditions":["outdoor participation","domestic overnight travel","equipment purchase"],"scenario_overlay":{"low":0.04,"base":0.16,"high":0.40}},
    {"case_id":"CROSS-08","description":"디지털기기 도입은 빠르지만 개인정보 우려가 높은 소비자","domains":["digital_devices_ai","social_creator"],"constraints":{},"output_unit":"person","semantic_conditions":["early device adoption","high privacy concern"],"scenario_overlay":{"low":0.08,"base":0.25,"high":0.55}},
    {"case_id":"CROSS-09","description":"네이버 플레이스는 있지만 CRM·홈페이지·온라인 판매가 없는 지방 소형 사업체","domains":["small_business_digital","career_professional"],"constraints":{},"output_unit":"enterprise","semantic_conditions":["local small enterprise","Naver Place present","CRM/website/online sales absent"],"scenario_overlay":{"low":0.01,"base":0.06,"high":0.20}},
    {"case_id":"CROSS-10","description":"은퇴 준비 금융행동과 가족돌봄·건강관리 부담이 결합된 50~60대 가구","domains":["finance_insurance","senior_retirement_care","health_wellness_care"],"constraints":{"age_min":50,"age_max":69},"output_unit":"household","semantic_conditions":["retirement financial preparation","family care burden","health-management burden"],"scenario_overlay":{"low":0.04,"base":0.15,"high":0.40}},
)
