/** KCA question-2 product IDs are zero-based here. Jobs are research hypotheses;
 * population and problem types come from the same published survey question. */
export const consumerJourneys = [
  {
    id: 'beauty',
    market: 'beauty',
    column: 26,
    label: '뷰티 선택·이용 중 불편',
    scope: '화장품·이미용·피부·체형관리 상품',
    job: '광고와 실제 경험의 차이 줄이기',
    hypothesis:
      '효과와 조건을 확인한 뒤 구매하도록 돕는 서비스가 실패 구매를 줄일까?',
    alternatives: '브랜드 설명, 뷰티 커뮤니티, 매장 상담, 소비자 상담',
    question: '문제 발생 품목, 재구매 중단, 최근 손실액과 유료 해결 의향은?',
    types: [
      ['advertising', '과장·기만 광고 경험'],
      ['price', '가격 대비 효용 불만'],
      ['redress', '교환·환불 해결 어려움'],
    ],
  },
  {
    id: 'clothing',
    market: 'beauty',
    column: 3,
    label: '의류·신발 구매 후 불편',
    scope: '의류·신발·가방',
    job: '받은 상품이 기대와 맞는 구매',
    hypothesis: '구매 전 품질 확인과 구매 후 교환 지원이 반복 실패를 줄일까?',
    alternatives: '판매처 문의, 오프라인 피팅, 교환·반품 접수',
    question: '품질·핏·사이즈 중 실제 문제의 원인과 반품 비용은?',
    types: [
      ['quality', '상품 품질 불량 경험'],
      ['redress', '교환·환불 해결 어려움'],
      ['delivery', '오배송·배송 지연 경험'],
    ],
  },
  {
    id: 'repair',
    market: 'home',
    column: 7,
    label: '주택수리·시공 중 불편',
    scope: '주택수리·인테리어 서비스',
    job: '약속한 조건대로 완성되는 시공',
    hypothesis: '견적·공정·검수 기록을 연결하면 계약 분쟁을 줄일 수 있을까?',
    alternatives: '시공업체, 중개 플랫폼, 제3자 검수, 분쟁조정',
    question: '공정별 분쟁 원인, 재시공 금액, 검수 서비스 지불 의향은?',
    types: [
      ['contract', '계약 불이행·부당행위 경험'],
      ['information', '시공 비교정보 부족'],
      ['price', '시공 가격 대비 불만'],
    ],
  },
  {
    id: 'appliance',
    market: 'home',
    column: 5,
    label: '가전 선택·사용 중 불편',
    scope: '가전제품',
    job: '제품 수명까지 고려하는 구매',
    hypothesis: '수리성과 유지 비용 정보를 구매 전에 비교할 가치가 있을까?',
    alternatives: '제조사 서비스센터, 판매처 비교, 사설 수리',
    question: '문제 제품의 수리 가능성·교체 비용과 유료 점검 의향은?',
    types: [
      ['quality', '가전 품질 불량 경험'],
      ['information', '구매 전 비교정보 부족'],
      ['redress', '교환·보상 해결 어려움'],
    ],
  },
  {
    id: 'fitness',
    market: 'fitness',
    column: 29,
    label: '운동시설 계약·이용 불편',
    scope: '헬스장·골프장·필라테스·요가 등 체육시설',
    job: '내 이용에 맞는 운동 계약',
    hypothesis: '계약 조건 확인과 중도 해지 지원이 회원권 선택을 도울까?',
    alternatives: '시설 상담, 단기 회원권, 소비자 상담',
    question: '환불 거부·위약금·시설 폐업 중 문제 유형과 손실 규모는?',
    types: [
      ['redress', '취소·환불 해결 어려움'],
      ['terms', '불리한 이용·계약 조건'],
      ['price', '이용 가격 대비 불만'],
    ],
  },
  {
    id: 'travel',
    market: 'travel',
    column: 28,
    label: '여행 예약·이용 중 불편',
    scope: '국내외 관광·항공권·숙박·패키지여행 서비스',
    job: '예약 조건과 실제 경험 맞추기',
    hypothesis: '조건 비교와 취소 지원이 여행 중 손실을 줄일 수 있을까?',
    alternatives: '여행사, 예약 플랫폼 고객센터, 여행자보험, 소비자 상담',
    question: '항공·숙박·체험 중 문제가 집중되는 단계와 회피 비용은?',
    types: [
      ['terms', '불리한 예약·거래 조건'],
      ['redress', '취소·환불 해결 어려움'],
      ['advertising', '광고와 실제 경험의 차이'],
    ],
  },
  {
    id: 'content_subscription',
    market: 'content',
    column: 30,
    label: '온라인 구독·오락서비스 이용 중 불편',
    scope: 'OTT·전자책·오디오북·게임·생성형 AI 등 온라인 구독·오락서비스',
    job: '구독 조건과 효용을 맞추기',
    hypothesis: '요금·해지·콘텐츠 조건을 비교하는 지원이 불필요한 구독을 줄일까?',
    alternatives: '서비스 앱, 통신사 결합, 구독 관리 앱, 고객센터',
    question: '요금 인상·자동갱신·해지 불편 중 실제 손실과 유료 해결 의향은?',
    types: [
      ['price', '가격 대비 효용 불만'],
      ['information', '구독 조건 비교정보 부족'],
      ['redress', '취소·환불 해결 어려움'],
    ],
  },
  {
    id: 'learning',
    market: 'education',
    column: 13,
    label: '교육 선택·계약 중 불편',
    scope: '학원·보습·온라인교육·스마트러닝 서비스',
    job: '수강 결정의 불확실성 줄이기',
    hypothesis: '강좌의 실제 내용·조건을 비교하는 지원에 수요가 있을까?',
    alternatives: '샘플 강의, 수강 후기, 교육기관 상담, 분쟁조정',
    question: '학습자와 결제자, 강의 품질·효과 불만과 해지 비용은?',
    types: [
      ['advertising', '과장·기만 광고 경험'],
      ['information', '수강 전 비교정보 부족'],
      ['redress', '수강 취소·환불 어려움'],
    ],
  },
  {
    id: 'insurance',
    market: 'finance',
    column: 21,
    label: '보험 이해·계약 중 불편',
    scope: '보험 상품',
    job: '보장과 계약 조건을 이해하기',
    hypothesis: '가입 전 설명과 조건 검토를 돕는 서비스가 불일치를 줄일까?',
    alternatives: '설계사 설명, 보험 비교 서비스, 약관, 소비자 상담',
    question: '보험 종류·계약 단계별 원인과 독립 검토에 대한 지불 의향은?',
    types: [
      ['explanation', '설명 부족·불완전 판매 경험'],
      ['information', '보험 비교정보 부족'],
      ['terms', '불리한 보험 거래조건'],
    ],
  },
  {
    id: 'banking',
    market: 'finance',
    column: 20,
    label: '금융상품 선택·이용 불편',
    scope: '예·적금·대출·투자 상품',
    job: '위험과 조건을 이해하는 금융 이용',
    hypothesis: '비교·설명·이상 징후 확인을 함께 지원할 수 있을까?',
    alternatives: '은행 상담, 금융 비교 서비스, 공시 정보, 소비자 상담',
    question: '상품별 실제 피해 여부와 문제를 예방하는 행동·비용은?',
    types: [
      ['privacy', '개인정보·사기 불안 경험'],
      ['information', '금융상품 비교정보 부족'],
      ['explanation', '설명 부족·불완전 판매 경험'],
    ],
  },
  {
    id: 'health_device',
    market: 'wellness',
    column: 9,
    label: '건강관리 기기 선택 불편',
    scope: '혈압·혈당 체크 등 디지털 헬스케어 기기',
    job: '내 관리에 적합한 기기 선택',
    hypothesis: '기기의 용도와 한계를 이해하는 구매 지원이 필요한가?',
    alternatives: '의료진 상담, 제조사 설명, 의료기기 판매점',
    question: '질환 관리용·생활 관리용 구분과 실제 사용 중단 이유는?',
    types: [
      ['advertising', '기기 광고에 대한 문제 경험'],
      ['information', '기기 비교정보 부족'],
      ['explanation', '설명 부족·불완전 판매 경험'],
    ],
  },
] as const;
