import type {
  ResearchBranch,
  ResearchMarket,
} from '../../lib/research-explorer';
import { consumerJourneys } from './consumer-journeys';
const b = (
  id: string,
  label: string,
  factors: string[],
  job: string,
  hypothesis: string,
  alternatives: string,
  nextQuestion: string,
  painMeasured = false,
  children?: ResearchBranch['children'],
): ResearchBranch => ({
  id,
  label,
  factors,
  job,
  hypothesis,
  alternatives,
  nextQuestion,
  painMeasured,
  ...(children ? { children } : {}),
});

/** Editorial jobs and proposed alternatives are product hypotheses. Population
 * comes exclusively from each explicit external factor, not these descriptions. */
const experienceMarkets: ResearchMarket[] = [
  {
    id: 'music',
    label: '음악·공연',
    unit: 'person',
    scope: '음악 감상·연주·연예공연 중 하나 이상 경험',
    branches: [
      b(
        'listen',
        '음악을 듣는 일상',
        ['leisure_G77'],
        '상황과 취향에 맞게 듣기',
        '음악 발견과 재생목록 관리에 반복되는 수고가 있는가?',
        '스트리밍 추천, 라디오, 지인 플레이리스트',
        '추천 결과를 바꾸기 위해 실제로 지출하거나 시간을 쓰는 순간은?',
      ),
      b(
        'play',
        '직접 연주하고 배우기',
        ['leisure_B12'],
        '혼자서도 실력이 느는 연습',
        '레슨 밖 연습 피드백이 학습 지속에 도움이 되는가?',
        '대면 레슨, 영상 강좌, 연습 앱',
        '연습 중단 이유와 최근 레슨·장비 지출을 확인하기',
      ),
      b(
        'live',
        '라이브 현장 경험',
        ['leisure_A8'],
        '좋아하는 공연을 놓치지 않기',
        '발견·예매·동행을 한 번에 해결할 수 있는가?',
        '티켓 판매처, 팬 커뮤니티, 공연장 알림',
        '연간 유료 관람 횟수와 예매 실패 경험은?',
      ),
    ],
  },
  {
    id: 'travel',
    label: '여행·로컬 경험',
    unit: 'person',
    scope: '국내여행 또는 아래 여가 여행 활동 경험',
    rootGroups: [['travel_domestic']],
    branches: [
      b(
        'nature',
        '자연·풍경·휴양',
        ['leisure_E39'],
        '일상에서 벗어나 회복하기',
        '혼잡도·날씨·체력에 맞는 자연 여행 선택이 어려운가?',
        '지도 리뷰, 여행사, 숙박 플랫폼',
        '숙소보다 이동·장비·체험에 돈을 쓰는 집단은 누구인가?',
      ),
      b(
        'culture',
        '역사·문화 탐방',
        ['leisure_E38'],
        '장소를 이해하는 여행',
        '관람 전후 맥락을 제공하는 소규모 해설 수요가 있는가?',
        '박물관 해설, 로컬 가이드, 여행 콘텐츠',
        '무료 해설로 해결되지 않는 경험과 유료 전환 계기는?',
      ),
      b(
        'camp',
        '국내 캠핑',
        ['leisure_E41'],
        '야외에서 머무르는 즐거움',
        '보관·설치·운반을 줄이는 장비 대여가 반복 이용될까?',
        '장비 구매, 캠핑장 대여, 글램핑',
        '장비 보유량, 연간 출정 횟수, 대여 가격 수용 범위는?',
      ),
      b(
        'overseas',
        '해외에서의 경험',
        ['leisure_E42'],
        '낯선 곳에서도 내 취향대로',
        '현지 언어·예약·동선의 불확실성을 줄일 수 있는가?',
        '패키지, 액티비티 플랫폼, 여행 커뮤니티',
        '독립 여행자가 실제 비용을 치르는 문제는 무엇인가?',
      ),
    ],
  },
  {
    id: 'fitness',
    label: '운동·아웃도어',
    unit: 'person',
    scope: '주 1회·30분 이상 규칙적 운동 참여',
    rootGroups: [['fitness']],
    branches: [
      b(
        'weight',
        '체중·체형 관리',
        ['need_fitness_weight'],
        '원하는 체형을 꾸준히 유지',
        '운동과 식생활을 잇는 피드백이 유지율을 높일까?',
        '헬스장, 개인 트레이닝, 식단 앱',
        '현재 대안의 중단률과 최근 유료 이용액은?',
        true,
      ),
      b(
        'stress',
        '운동으로 스트레스 해소',
        ['need_fitness_stress'],
        '마음까지 가벼워지는 운동',
        '강도보다 회복 경험을 원하는 운동 프로그램이 필요한가?',
        '산책, 요가, 러닝 모임',
        '스트레스 해소 목적이 서비스 선택과 지불로 이어지는가?',
        true,
      ),
      b(
        'hiking',
        '등산·트레킹',
        ['int_fitness_hiking'],
        '안전하고 즐겁게 산행하기',
        '체력과 장비 수준에 맞는 코스·동행 연결은 유용한가?',
        '등산 모임, 지도 앱, 전문 매장',
        '산행 빈도와 장비 교체·가이드 지출은?',
      ),
      b(
        'gym',
        '헬스·개인 운동',
        ['int_fitness_gym'],
        '실행할 수 있는 운동 루틴',
        '진행 상황을 이해하는 피드백이 재등록에 영향을 줄까?',
        '헬스장, PT, 홈트 영상',
        '기존 회원권 미사용 이유와 지속 의향은?',
      ),
    ],
  },
  {
    id: 'content',
    label: '영상·콘텐츠',
    unit: 'person',
    scope: '무료 동영상을 포함한 OTT 이용',
    rootGroups: [['content']],
    branches: [
      b(
        'paid',
        '돈을 내고 보는 콘텐츠',
        ['ott_paid'],
        '원하는 작품에 쉽게 접근',
        '여러 서비스의 콘텐츠 탐색을 줄일 수 있는가?',
        'OTT 앱, 통합 검색, 콘텐츠 커뮤니티',
        '작품 탐색과 다중 구독에 드는 비용은?',
      ),
      b(
        'price',
        'OTT 지불금액 증가 경험',
        ['need_ott_price'],
        '구독 비용의 효용 판단',
        '요금이 오른 이용자에게 구독 선택 지원이 필요한가?',
        '직접 해지·재구독, 통신사 결합',
        '비용 증가가 불만·해지·대안 구매로 이어지는 비율은?',
      ),
      b(
        'short',
        '짧은 영상 소비',
        ['int_content_short'],
        '짧은 시간 안에 즐기고 발견',
        '발견한 정보를 저장하고 다시 찾는 과정이 불편한가?',
        '플랫폼 저장, 메신저 공유, 메모 앱',
        '반복되는 재탐색 문제에 유료 수요가 있는가?',
      ),
    ],
  },
  {
    id: 'gaming',
    label: '게임',
    unit: 'person',
    scope: '최근 1년 게임 이용, 20~69세',
    rootGroups: [['gaming']],
    branches: [
      b(
        'mobile',
        '모바일 플레이',
        ['int_gaming_mobile'],
        '일상 사이의 플레이',
        '짧은 세션에서도 성취와 연결을 얻고 싶은가?',
        '기존 모바일 게임, 길드, 커뮤니티',
        '장르별 결제율과 과금 유지 기간은?',
      ),
      b(
        'safety',
        '게임 내 사이버폭력 경험',
        ['need_gaming_safety'],
        '안전한 플레이 환경',
        '신고 이후 대응과 보호를 개선할 수 있는가?',
        '게임사 신고, 차단, 길드 운영',
        '피해 빈도·미해결률과 게임사 도입 의향은?',
        true,
      ),
      b(
        'unresolved',
        '피해 후 별도 대응 없음',
        ['arc_gaming_unresolved'],
        '대응할 수 있는 도움',
        '대응하지 않은 이유가 절차·효과에 대한 불신인가?',
        '무시하기, 게임 이탈, 자체 커뮤니티',
        '대응하지 않은 이유를 인터뷰로 구분하기',
        true,
      ),
      b(
        'console',
        '콘솔 플레이',
        ['gaming_console'],
        '몰입할 만한 게임 경험',
        '신작·장비·동행 선택에서 남는 수요가 있는가?',
        '콘솔 스토어, 게임 리뷰, 중고 거래',
        '연간 게임 구입 횟수와 장비 교체 주기는?',
      ),
    ],
  },
  {
    id: 'beauty',
    label: '뷰티·패션',
    unit: 'person',
    scope: '온라인 화장품 구매 또는 미용 활동 경험. 전체 화장품 사용률은 아님',
    branches: [
      b(
        'skin',
        '피부·헤어·뷰티 관리',
        ['leisure_F67'],
        '나에게 맞는 관리 찾기',
        '제품·서비스 선택에서 효과 확인이 어려운가?',
        '뷰티 매장, 미용 서비스, 리뷰 콘텐츠',
        '피부·헤어·네일별 최근 결제 경험과 불만 강도를 분리하기',
      ),
      b(
        'cosmetics',
        '온라인 화장품 구매',
        ['cosmetics_online_buyers'],
        '내 피부에 맞는 제품 구매',
        '반복 구매와 새 제품 탐색을 다르게 도와야 하는가?',
        '온라인몰, 브랜드몰, 뷰티 커뮤니티',
        '성별·품목별 구매 주기와 실패 구매 비용은?',
      ),
    ],
  },
  {
    id: 'garden',
    label: '가드닝·식물',
    unit: 'person',
    scope: '지난 1년 식물 키우기·가꾸기 경험',
    branches: [
      b(
        'plants',
        '식물을 키우는 생활',
        ['leisure_F70'],
        '식물을 건강하게 오래 키우기',
        '빛·물·병해를 이해하는 관리 지원이 필요한가?',
        '화원, 영상 가이드, 식물 커뮤니티',
        '최근 식물 손실과 관리용품·상담 지출을 확인하기',
      ),
      b(
        'club',
        '모임과 함께하는 원예',
        ['leisure_F70', 'leisure_H86'],
        '함께 배우고 나누기',
        '모임 참여자와 식물 경험자의 교집합에 교환·체험 수요가 있는가?',
        '원예 동호회, 지역 클래스, 교환 모임',
        '두 활동의 실제 교집합과 유료 모임 참여 여부를 확인하기',
      ),
    ],
  },
  {
    id: 'education',
    label: '배움·자기계발',
    unit: 'person',
    scope: '최근 1년 평생학습 프로그램 참여, 25~79세',
    rootGroups: [['education']],
    branches: [
      b(
        'career',
        '직업과 연결되는 학습',
        ['int_education_career'],
        '업무에 쓸 수 있는 역량',
        '학습 성과를 실제 업무와 연결하는 지원이 필요한가?',
        '직무 강좌, 자격 과정, 사내 교육',
        '완강 이후 업무 성과와 개인·회사 결제 주체는?',
      ),
      b(
        'hobby',
        '취미·여가·스포츠 학습',
        ['learn_hobby'],
        '좋아하는 것을 계속 배우기',
        '첫 체험 이후 지속 참여를 돕는 서비스가 필요한가?',
        '문화센터, 지역 클래스, 온라인 강의',
        '재등록률·수업 외 실천 빈도·실제 지출은?',
      ),
      b(
        'reading',
        '독서와 함께하는 배움',
        ['education', 'leisure_F65'],
        '읽은 것을 내 것으로 만들기',
        '독서와 프로그램 참여를 연결하면 유지될까?',
        '독서모임, 도서관, 독서 앱',
        '독서·학습의 실제 교집합과 유료 모임 수요는?',
      ),
    ],
  },
  {
    id: 'home',
    label: '집·인테리어',
    unit: 'person',
    scope: '실내 장식 변경 또는 생활공예 경험. 전체 주거 소비자 수가 아님',
    branches: [
      b(
        'decor',
        '공간을 꾸미기',
        ['leisure_F54'],
        '내 생활에 맞게 공간 바꾸기',
        '배치·재료·시공 결과를 미리 확인하고 싶은가?',
        '인테리어 플랫폼, 가구 매장, 셀프 시공',
        '최근 공간 변경 예산과 실패·재작업 비용은?',
      ),
      b(
        'craft',
        '생활 속 직접 제작',
        ['leisure_F50'],
        '쓸모 있는 물건을 직접 만들기',
        '재료·도구·제작 피드백을 묶는 방식이 유용한가?',
        '공방, DIY 키트, 영상 강좌',
        '도구 보유와 반복 재료 구매 규모를 확인하기',
      ),
    ],
  },
  {
    id: 'photo',
    label: '사진·창작',
    unit: 'person',
    scope: '카메라 취미 촬영 또는 미술 활동 경험. 휴대폰 촬영 전체 제외',
    branches: [
      b(
        'camera',
        '카메라로 기록하기',
        ['leisure_B14'],
        '원하는 장면을 제대로 남기기',
        '장비 구매보다 촬영 경험의 완성이 더 중요한가?',
        '카메라 매장, 사진 강좌, 출사 모임',
        '장비 지출과 촬영·편집 서비스 지출을 분리하기',
      ),
      b(
        'art',
        '미술·시각 창작',
        ['leisure_B11'],
        '생각을 작품으로 표현하기',
        '창작 피드백과 발표 기회가 부족한가?',
        '공방, 미술 학원, 창작 플랫폼',
        '재료비·수강료·전시 참여 지출과 지속 빈도는?',
      ),
    ],
  },
  {
    id: 'collect',
    label: '수집·취미용품',
    unit: 'person',
    scope: '수집·생활공예·낚시 중 하나 이상 경험',
    branches: [
      b(
        'objects',
        '좋아하는 물건 수집',
        ['leisure_F49'],
        '가치 있는 수집을 지속하기',
        '진품·상태·보관·거래 중 가장 큰 불편은 무엇인가?',
        '전문점, 중고 플랫폼, 수집 커뮤니티',
        '수집 품목별 연간 거래액과 검증 비용은?',
      ),
      b(
        'fishing',
        '낚시·장비 취미',
        ['leisure_F56'],
        '상황에 맞는 낚시 경험',
        '지역·시즌·숙련도에 맞는 장비 선택을 도울 수 있는가?',
        '낚시점, 선상 예약, 낚시 모임',
        '출조 횟수와 장비·교통·선비 지출을 구분하기',
      ),
      b(
        'craft',
        '공예·제작 취미',
        ['leisure_F50'],
        '직접 만드는 취미',
        '재료 탐색과 남는 도구의 비용을 줄일 수 있는가?',
        '공방, 키트, 공동 작업실',
        '키트 재구매와 도구 공유에 대한 실제 수요는?',
      ),
    ],
  },
  {
    id: 'community',
    label: '모임·지역서비스',
    unit: 'person',
    scope: '동호회·사교모임·봉사 중 하나 이상 경험',
    branches: [
      b(
        'club',
        '취향으로 만나는 모임',
        ['leisure_H86'],
        '관심이 통하는 사람 만나기',
        '첫 참석과 반복 참석 사이의 이탈을 줄일 수 있는가?',
        '동호회, 소모임 앱, 지역 게시판',
        '참여 동기와 회비·장소비 지출은?',
      ),
      b(
        'social',
        '지속되는 사교 관계',
        ['leisure_H82'],
        '관계를 이어가는 시간',
        '일정·장소·구성원 조율의 수요가 있는가?',
        '메신저, 단체 예약, 기존 지인 모임',
        '주최자와 참석자 중 누가 비용을 지불하는가?',
      ),
      b(
        'volunteer',
        '지역에서 기여하기',
        ['leisure_H80'],
        '의미 있게 참여하기',
        '관심과 시간에 맞는 봉사 활동 연결이 필요한가?',
        '봉사 포털, 지역 기관, 단체',
        '참여 중단 이유와 기관의 운영 예산은?',
      ),
    ],
  },
  {
    id: 'wellness',
    label: '건강·휴식',
    unit: 'person',
    scope: '산책·목욕/사우나 중 하나 이상 여가 경험. 의료 수요 제외',
    branches: [
      b(
        'walk',
        '일상 속 휴식 산책',
        ['leisure_G71'],
        '짧게라도 회복하는 일상',
        '생활 반경에서 휴식의 질을 높일 수 있는가?',
        '공원, 걷기 앱, 동네 모임',
        '무료 산책을 넘어서 지불하는 편익은 무엇인가?',
      ),
      b(
        'spa',
        '목욕·사우나·찜질방',
        ['leisure_G72'],
        '몸을 쉬게 하는 시간',
        '시설·혼잡·위생 정보를 더 쉽게 비교하고 싶은가?',
        '동네 목욕탕, 사우나, 스파 예약',
        '방문 주기와 회당 결제액, 선택 기준은?',
      ),
    ],
  },
  {
    id: 'commerce',
    label: '쇼핑·커머스',
    unit: 'person',
    scope: '최근 1년 인터넷 쇼핑 이용 성인',
    rootGroups: [['commerce']],
    branches: [
      b(
        'online',
        '온라인으로 구매하는 생활',
        ['commerce'],
        '필요한 것을 적절한 조건에 구매',
        '빠른 반복 구매와 신중한 신규 구매의 요구가 다른가?',
        '종합몰, 가격 비교, 브랜드몰',
        '품목별 반복 구매·검색·반품 비용을 확인하기',
        false,
        [
          { id: 'pc', label: 'PC 인터넷쇼핑', factors: ['kca_channel_pc'] },
          { id: 'mobile', label: '모바일쇼핑', factors: ['kca_channel_mobile'] },
          { id: 'sns', label: 'SNS 플랫폼 쇼핑', factors: ['kca_channel_sns'] },
          { id: 'c2c', label: '개인간 거래 플랫폼 쇼핑', factors: ['kca_channel_c2c'] },
          {
            id: 'pc_quality',
            label: 'PC · 품질 문제 경험',
            factors: ['kca_channel_pc', 'kca_channel_pc_quality'],
          },
          {
            id: 'pc_delivery',
            label: 'PC · 배송 문제 경험',
            factors: ['kca_channel_pc', 'kca_channel_pc_delivery'],
          },
          {
            id: 'pc_price',
            label: 'PC · 가격 문제 경험',
            factors: ['kca_channel_pc', 'kca_channel_pc_price'],
          },
          {
            id: 'mobile_quality',
            label: '모바일 · 품질 문제 경험',
            factors: ['kca_channel_mobile', 'kca_channel_mobile_quality'],
          },
          {
            id: 'mobile_delivery',
            label: '모바일 · 배송 문제 경험',
            factors: ['kca_channel_mobile', 'kca_channel_mobile_delivery'],
          },
          {
            id: 'mobile_price',
            label: '모바일 · 가격 문제 경험',
            factors: ['kca_channel_mobile', 'kca_channel_mobile_price'],
          },
          {
            id: 'sns_quality',
            label: 'SNS · 품질 문제 경험',
            factors: ['kca_channel_sns', 'kca_channel_sns_quality'],
          },
          {
            id: 'sns_price',
            label: 'SNS · 가격 문제 경험',
            factors: ['kca_channel_sns', 'kca_channel_sns_price'],
          },
          {
            id: 'sns_redress',
            label: 'SNS · 환불 문제 경험',
            factors: ['kca_channel_sns', 'kca_channel_sns_redress'],
          },
          {
            id: 'c2c_redress',
            label: '개인간 거래 · 환불 문제 경험',
            factors: ['kca_channel_c2c', 'kca_channel_c2c_redress'],
          },
          {
            id: 'c2c_quality',
            label: '개인간 거래 · 품질 문제 경험',
            factors: ['kca_channel_c2c', 'kca_channel_c2c_quality'],
          },
          {
            id: 'c2c_price',
            label: '개인간 거래 · 가격 문제 경험',
            factors: ['kca_channel_c2c', 'kca_channel_c2c_price'],
          },
        ],
      ),
      b(
        'cosmetics',
        '온라인 화장품 구매',
        ['cosmetics_online_buyers'],
        '제품 효과와 구매 조건 판단',
        '효과 검증이 가격 할인보다 중요해지는 순간은?',
        '뷰티몰, 리뷰 커뮤니티, 오프라인 체험',
        '실패 구매 경험과 재구매 품목은?',
      ),
      b(
        'offline',
        '여가 쇼핑·외식도 즐기는 이용자',
        ['commerce', 'leisure_F63'],
        '온라인과 현장을 오가기',
        '발견은 현장에서, 구매는 온라인에서 이루어지는가?',
        '오프라인 매장, 팝업, 쇼핑 앱',
        '두 행동의 실제 연결과 구매 전환 경로를 확인하기',
      ),
    ],
  },
  {
    id: 'mobility',
    label: '드라이브·모빌리티',
    unit: 'person',
    scope: '여가 목적 자동차 드라이브 경험. 차량 소유·정비시장 전체 제외',
    branches: [
      b(
        'drive',
        '드라이브로 떠나기',
        ['leisure_E48'],
        '차로 접근하는 여가',
        '주차·휴식·경관을 잇는 동선 지원이 필요한가?',
        '지도 앱, 여행 커뮤니티, 로컬 콘텐츠',
        '운전자·동승자 비중과 여행 중 부대 지출은?',
      ),
      b(
        'camp',
        '드라이브와 캠핑의 교집합',
        ['leisure_E48', 'leisure_E41'],
        '차와 야외생활을 연결하기',
        '운반·보관·설치 부담을 줄일 수 있는가?',
        '캠핑 장비, 렌터카, 글램핑',
        '두 활동의 실제 교집합과 차량·장비 이용 형태는?',
      ),
    ],
  },
  {
    id: 'food',
    label: '외식·미식',
    unit: 'person',
    scope: '개인적으로 음식점에서 식사하는 20~79세. 가족 외식·배달 지출과 별도',
    rootGroups: [['food_dining']],
    branches: [
      b(
        'taste',
        '맛을 즐기는 외식',
        ['food_dining_taste'],
        '내 취향에 맞는 한 끼',
        '리뷰의 평점보다 취향·메뉴·동행 맥락이 선택에 도움이 되는가?',
        '지도 리뷰, 맛집 콘텐츠, 지인 추천',
        '식사 장소를 바꾸게 만드는 이유와 최근 실패 경험은?',
        true,
        [
          {
            id: 'weekly',
            label: '매주 즐기는 외식',
            factors: ['food_dining_weekly'],
          },
          {
            id: 'presearch',
            label: '식당 정보를 먼저 검토',
            factors: ['research_presearch'],
          },
          {
            id: 'review',
            label: '후기를 참고하는 선택',
            factors: ['research_review'],
          },
        ],
      ),
      b(
        'work',
        '근무·학업 사이 한 끼',
        ['food_dining_work'],
        '제때 빠르게 먹기',
        '혼잡·대기·영양 균형을 함께 해결할 수 있는가?',
        '구내식당, 근처 식당, 도시락',
        '시간대별 대기 비용과 반복 결제 주체는?',
        true,
        [
          {
            id: 'weekly',
            label: '주 1회 이상 식사',
            factors: ['food_dining_weekly'],
          },
          {
            id: 'online',
            label: '온라인 구매에 익숙한 층',
            factors: ['commerce'],
          },
        ],
      ),
      b(
        'occasion',
        '특별한 날의 외식',
        ['food_dining_occasion'],
        '함께하는 날을 잘 준비',
        '동행 구성·예산·예약 조건을 한 번에 맞추는 수요가 있는가?',
        '예약 플랫폼, 호텔 식음, 레스토랑 상담',
        '행사별 객단가와 예약 변경·취소 경험은?',
        true,
        [
          {
            id: 'presearch',
            label: '예약 전 정보를 검토',
            factors: ['research_presearch'],
          },
          {
            id: 'review',
            label: '후기를 참고하는 선택',
            factors: ['research_review'],
          },
        ],
      ),
      b(
        'cook',
        '외식과 요리를 함께 즐기기',
        ['food_dining', 'leisure_F51'],
        '만들고 맛보는 즐거움',
        '재료 탐색·소분·배움 중 반복 비용이 큰 부분은?',
        '레시피 콘텐츠, 식재료몰, 쿠킹 클래스',
        '취미 요리 경험과 일상 집밥·외식 소비를 구분해 조사하기',
      ),
    ],
    gap: '카페·파인다이닝 단독 고객과 요리 취미 지출은 별도 근거가 필요합니다. 외식 목적별 금액은 연령별 외식 지출 평균을 전이한 범위입니다.',
  },
  {
    id: 'pet',
    label: '반려동물',
    unit: 'household',
    scope: '현재 반려동물을 양육하는 일반가구',
    rootGroups: [['pet_household']],
    branches: [
      b(
        'dog',
        '반려견과 사는 가구',
        ['pet_dog_household'],
        '반려견의 건강한 일상',
        '산책·훈련·돌봄 공백 중 반복 수요는 무엇인가?',
        '동물병원, 펫시터, 훈련소',
        '가구당 양육비와 개체별 나이·건강·돌봄 공백을 확인하기',
      ),
      b(
        'cat',
        '반려묘와 사는 가구',
        ['pet_cat_household'],
        '반려묘에 맞는 생활환경',
        '먹이·화장실·건강 변화 관찰을 도울 수 있는가?',
        '동물병원, 용품몰, 반려묘 커뮤니티',
        '소모품 구매 주기와 건강관리 비용은?',
      ),
    ],
  },
  {
    id: 'family',
    label: '가족·돌봄',
    unit: 'household',
    scope:
      '18세 이하 자녀 또는 65세 이상 가구원이 있는 일반가구. 실제 돌봄 필요·구매 가구와 별도',
    branches: [
      b(
        'children',
        '자녀가 있는 생활',
        ['family_children'],
        '일과 자녀의 하루 조율',
        '등하원·방과 후 공백에서 해결되지 않는 수요는?',
        '보육기관, 가족 돌봄, 학원, 공공 아이돌봄',
        '자녀 연령·맞벌이·미충족 돌봄 시간·결제 주체를 확인하기',
        false,
        [
          {
            id: 'preschool',
            label: '5세 이하 자녀가 있는 가구',
            factors: ['family_preschool'],
          },
        ],
      ),
      b(
        'elder',
        '고령 가족과의 생활',
        ['family_elder'],
        '안전한 일상과 가족 연결',
        '동행·식사·건강 관리 중 가족이 비용을 쓰는 문제는?',
        '가족 지원, 방문요양, 지역 복지서비스',
        '건강·자립 수준과 공공지원 밖의 수요는?',
        false,
        [
          {
            id: 'only',
            label: '65세 이상 구성원만 동거',
            factors: ['family_elder_only'],
          },
          {
            id: 'alone',
            label: '65세 이상 1인 생활',
            factors: ['family_elder_alone'],
          },
        ],
      ),
    ],
    gap: '가족 구성은 관측했지만 미충족 돌봄과 유료 구매율은 미확보입니다. 가족 상황을 곧바로 돌봄 서비스 수요로 해석하지 않습니다.',
  },
  {
    id: 'delivery',
    unionModel: 'overlap_bounds',
    label: '배달·간편식',
    unit: 'household',
    scope:
      '가족 배달·포장 또는 아래 간편식 구매 경험 일반가구. 개인 배달 식사와 별도',
    branches: [
      b(
        'delivery',
        '가족과 배달·포장 식사',
        ['food_delivery_household'],
        '가족의 한 끼를 빠르게 해결',
        '서로 다른 메뉴·시간·예산을 맞추기 어려운가?',
        '배달 앱, 음식점 전화 주문, 직접 포장',
        '가족 구성별 반복 주문·배달료·대기 시간의 영향은?',
        false,
        [
          {
            id: 'weekly',
            label: '주 1회 이상 반복 식사',
            factors: ['food_delivery_weekly'],
          },
          {
            id: 'app',
            label: '앱으로 배달 주문',
            factors: ['food_delivery_app'],
          },
          {
            id: 'phone',
            label: '전화로 배달 주문',
            factors: ['food_delivery_phone'],
          },
        ],
      ),
      b(
        'heat',
        '데워 먹는 간편식',
        ['hmr_heat'],
        '준비를 줄이면서 따뜻하게',
        '소분·보관·영양의 균형에서 남는 수요는?',
        '냉동식품, 즉석조리식품, 반찬가게',
        '반복 구매 품목·폐기율·1회 식비를 확인하기',
        false,
        [
          {
            id: 'weekly',
            label: '주 1회 이상 구매',
            factors: ['hmr_heat_weekly'],
          },
        ],
      ),
      b(
        'ready',
        '바로 먹는 간편식',
        ['hmr_ready'],
        '준비 없이 바로 한 끼',
        '양·신선도·수령 시점 때문에 대안을 찾는가?',
        '편의점 도시락, 샌드위치, 샐러드',
        '시간대별 이용 빈도와 프리미엄 지불 조건은?',
        false,
        [
          {
            id: 'weekly',
            label: '주 1회 이상 구매',
            factors: ['hmr_ready_weekly'],
          },
        ],
      ),
      b(
        'kit',
        '직접 완성하는 밀키트',
        ['hmr_kit'],
        '요리하는 즐거움과 간편함',
        '재료 손질·남는 재료·메뉴 다양성 중 중요한 문제는?',
        '밀키트, 레시피, 소분 식재료',
        '체험 이후 재구매와 직접 요리 대비 총비용은?',
        false,
        [
          {
            id: 'weekly',
            label: '주 1회 이상 구매',
            factors: ['hmr_kit_weekly'],
          },
        ],
      ),
    ],
    gap: '간편식의 각 품목은 중복 구매 가능합니다. 배달 월 지출을 간편식 구매 가구의 지출로 대체하지 않습니다.',
  },
  {
    id: 'finance',
    label: '개인 재테크',
    unit: 'person',
    scope:
      '최근 1년 인터넷뱅킹 이용 성인. 주식·저축·유료 자문 고객 전체를 뜻하지 않음',
    rootGroups: [['finance_banking']],
    branches: [
      b(
        'banking',
        '계좌와 일상 자금 관리',
        ['finance_banking'],
        '돈의 흐름을 이해하고 관리',
        '흩어진 계좌·납부·저축 결정을 쉽게 볼 수 있는가?',
        '은행 앱, 가계부, 마이데이터 서비스',
        '거래 자체보다 이용자가 시간·비용을 치르는 판단은?',
        false,
        [
          {
            id: 'mobile',
            label: '모바일로 은행 거래',
            factors: ['finance_mobile'],
          },
          {
            id: 'presearch',
            label: '정보 검토 성향',
            factors: ['research_presearch'],
          },
        ],
      ),
      b(
        'mobile',
        '모바일 금융의 일상',
        ['finance_mobile'],
        '안전하고 확실하게 거래',
        '인증·이체 확인·상품 이해에서 반복되는 어려움은?',
        '은행 앱, 상담센터, 지점 방문',
        '사용 경험·문제 발생·추가 지불 의향을 분리해 조사하기',
      ),
    ],
    gap: '디지털 은행 이용의 분모를 확보했습니다. 주식 보유·연금·저축 및 금융 자문 결제는 별도 조사 필요. 금융 거래액·자산은 소비 지출이 아닙니다.',
  },
];

/** A problem cohort is its own observed branch, never an arbitrary problem
 * rate applied to the market's other activity cohorts. The root is their OR. */
export const researchMarkets: ResearchMarket[] = experienceMarkets.map(
  (market) => {
    const journeys = consumerJourneys.filter((j) => j.market === market.id);
    if (!journeys.length) return market;
    return {
      ...market,
      scope:
        market.scope +
        ' · 별도 품목 문제 경험 집단 포함. 표시된 수요의 합집합이며 산업 전체 이용자 수는 아님',
      unionModel: 'overlap_bounds',
      branches: [
        ...market.branches,
        ...journeys.map((j) => ({
          ...b(
            'problem_' + j.id,
            j.label,
            ['kca_' + j.id],
            j.job,
            j.hypothesis,
            j.alternatives,
            j.question,
            true,
            j.types.map(([type, label]) => ({
              id: type,
              label,
              factors: ['kca_' + j.id + '_' + type],
            })),
          ),
          evidenceType: 'consumer_problem' as const,
        })),
      ],
    };
  },
);
